In [ ]:
'''numpy: numpy is also called as numerical python.
it is also used to do thr mathematical operatins on arrays.
Why numpy? Why not lists?
numpy arrays are 50 times faster then lists and also numpy is more memory-efficient. 
Where lists are not efficient.'''
#Creation of numpy
import numpy as np
a=np.array(2)# It is a one dimentional array
b=np.array([1,2,3,4,5,6,7,8,9,10,11])# It is a 1 dimentional array
c=np.array([[1,2,3],[4,5,6]])# It is 2D array
d=np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])# It is a 3D array
# We can create N number of array with N dimentions
print(a)
print(b)
print(c)
print(d)

In [3]:
#asarray(array, dtype = datatype,order="C or F")
e = np.asarray(d,dtype=float,order="C")
f =  np.asarray(d,dtype=float,order="F")
print(e)
'''nditer(array)
We have to use nditer() with asarray()'''
print(f'the array after applying np.nditr() for columns')
for i in np.nditer(e):
    print(i)
print(f'the array after applying np.nditr() for rows')
for i in np.nditer(f):
    print(f)

[[[[ 1.  2.  3.]
   [ 4.  5.  6.]]

  [[ 7.  8.  9.]
   [10. 11. 12.]]]]
the array after applying np.nditr() for columns
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
the array after applying np.nditr() for rows
[[[[ 1.  2.  3.]
   [ 4.  5.  6.]]

  [[ 7.  8.  9.]
   [10. 11. 12.]]]]
[[[[ 1.  2.  3.]
   [ 4.  5.  6.]]

  [[ 7.  8.  9.]
   [10. 11. 12.]]]]
[[[[ 1.  2.  3.]
   [ 4.  5.  6.]]

  [[ 7.  8.  9.]
   [10. 11. 12.]]]]
[[[[ 1.  2.  3.]
   [ 4.  5.  6.]]

  [[ 7.  8.  9.]
   [10. 11. 12.]]]]
[[[[ 1.  2.  3.]
   [ 4.  5.  6.]]

  [[ 7.  8.  9.]
   [10. 11. 12.]]]]
[[[[ 1.  2.  3.]
   [ 4.  5.  6.]]

  [[ 7.  8.  9.]
   [10. 11. 12.]]]]
[[[[ 1.  2.  3.]
   [ 4.  5.  6.]]

  [[ 7.  8.  9.]
   [10. 11. 12.]]]]
[[[[ 1.  2.  3.]
   [ 4.  5.  6.]]

  [[ 7.  8.  9.]
   [10. 11. 12.]]]]
[[[[ 1.  2.  3.]
   [ 4.  5.  6.]]

  [[ 7.  8.  9.]
   [10. 11. 12.]]]]
[[[[ 1.  2.  3.]
   [ 4.  5.  6.]]

  [[ 7.  8.  9.]
   [10. 11. 12.]]]]
[[[[ 1.  2.  3.]
   [ 4.  5.  6.]]

  [[ 7.  8.  9.]


In [ ]:
#frombuffer(array, dtype = int,count=5,offset=2)
print( np.frombuffer(b,dtype = "S1",count=3,offset=2))
print()