# Pattern-1

In [ ]:
'''
when we print(i)
1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 
6 6 6 6 6 6

when we print(j)

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 
1 2 3 4 5 6 

'''

In [1]:
n = int(input("enter a number:"))
for i in range(1,n+1):
    for j in range(1,i+1):
        print(i,end=' ')
#         print(j,end=' ')
    print()

enter a number:5
1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


# Pattern-2

In [6]:
n= int(input())
s=0
for i in range(0,n+1):
    for j in range(i):
        s+=i
        print(s,end=' ')
    print()

5

1 
3 5 
8 11 14 
18 22 26 30 
35 40 45 50 55 


# List

In [ ]:
'''
list : Collection of different datatypes into a single varible and enclosed in square brackets and the data is separated by\
comma is called list

list is declared by using '[]'
list is hetrogenous datatype
List is mutable
list is ordered
list is indexed
list allows duplicate values
'''

In [1]:
l = [1,2,3,4,5,6,7,8,9]
print(l[1:-6:-1]) # start:stop:stepsize

[2]


# Rotate the elements of the list by k times

In [51]:
def swap(k,l):   
    lst = l[len(l)-k:] + l[:len(l)-k]
    return lst
    lst1 = l[k:] + l[:k]
    return lst1
lst = [2,3,4,5,10]
n = int(input())
print(swap(n,lst))

2
[5, 10, 2, 3, 4]


# left Rotate

In [48]:
l = [2,3,4,5,10]
k = int(input())
lst1 = l[k:] + l[:k]
print(lst1)

2
[4, 5, 10, 2, 3]


In [53]:
# 1.remove duplicate from the lst
lst = [1,2,3,3,2,3,1,5,5,4,4]
l = []
for i in lst:
    if i not in l:
        l.append(i)
print(l)


lst1 = [1,1,1,1,5,5,5,5,6,6,6,6,7,7,7]
print(list(set(lst1)))

[1, 2, 3, 5, 4]
[1, 5, 6, 7]


In [56]:
# 2. sum of even elements in the list
lst = [1,2,3,4,5,6,7,8,9,10]
print(sum(lst)) # total sum

lls = []
for i in lst:
    if i % 2 == 0:
        lls.append(i)
print(sum(lls)) # even number sum

55
30


In [57]:
# 3. sum of odd elements in the list
lst = [1,2,3,4,5,6,7,8,9,10]
ls = []
for i in lst:
    if i % 2 !=0:
        ls.append(i)
print(sum(ls)) # odd number sum

25


In [58]:
# 4. seperate the even and odd numbers from the list
lst = [1,2,3,4,5,6,7,8,9,10]
even = []
odd = []
for i in lst:
    if i % 2 == 0:
        even.append(i)
    else:
        odd.append(i)
print(even)
print(odd)

[2, 4, 6, 8, 10]
[1, 3, 5, 7, 9]


In [61]:
# 5.count the number of elements in the list
lst = [1,2,3,4,5,6,7,8,9,10]
print(len(lst)) # built-in method

c = 0
for i in lst:
    c+=1
print(c) # without using built-in method

10
10


In [63]:
#6. Total sum in the lst
lst = [1,2,3,4,5,6,7,8,9,10]
print(sum(lst)) # built-in method

s = 0
for i in lst:
    s+=i
print(s) # without using buit-in method

55
55


In [65]:
# 7,8 max and min in list
lst = [1,2,3,4,5,6,7,8,9,10]
print(max(lst))
print(min(lst))
ma = lst[0]
for i in l

10
1


In [68]:
# 9.left rotation of the lst

l = [2,3,4,5,10]
k = int(input())
lst1 = l[k:] + l[:k]
print(lst1)

2
[4, 5, 10, 2, 3]


In [67]:
# 10. right rotation of the lst
l = [2,3,4,5,10]
d = 2
lst = l[len(l)-d:]+l[:len(l)-d]
print(lst)

[5, 10, 2, 3, 4]


In [90]:
import numpy as np
a = list(map(int,input().split()))
mat = np.array(a).reshape(3,3)
print(mat)
print(np.trace(mat))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [102]:
s=0
for i in range(0,3):
    for j in range(0,3):
        s=s+1
        print(s,end=' ')
    print()

1 2 3 
4 5 6 
7 8 9 


In [118]:
# find the sum of first and last element and continue upto middle
l=list(map(int,input().split(' ')))
i =1
j =-1
s = []
for i in range(len(l)):
    a= l[i]+l[j]
    i+=1
    j-=1
    s.append(a)
print(s)

1 2 3 4 5
[6, 6, 6, 6, 6]


In [128]:
l=[1,2,3,4,5,6,7]
i=0;j=-1
if len(l)%2==0:
    c=len(l)//2
else:
    c=len(l)//2+1
for k in range(c):
    b=l[i]+l[j]
    i+=1
    j-=1
    print(b)

8
8
8
8


In [1]:
l= [1,2,3,4,5,6,7]
l2= l[len(l)//2]
print(2*l2)

8


# Formation of matrix

In [26]:
def read(l,row,cols):
    for i in range(row):
        t= list(map(int,input().split()))
        l.append(t)
def printm(l,row,col):
    for i in range(row):
        for j in range(col):
            print(l[i][j],end=',')
        print()
def sum(l,row,col):
    s=0
    for i in range(row):
        for j in range(col):
            s=+l[i][j]
        print()
    return s
def sumoppositediagonal(l,row,col):
    if len(l) != len(l[0]):
        raise ValueError("Matrix must be square for opposite diagonal sum")
    n = len(l)
    diagonal_sum = 0
    for i in range(n):
        diagonal_sum += l[i][n - 1 - i]
    return diagonal_sum
row= int(input("enter no.of rows"))
col=int(input("enter no.of columns"))
l=[]
read (l,row,col)
print(l,row,col)
print(sum(l,row,col))
sumoppositediagonal(l,row,col)


enter no.of rows2
enter no.of columns2
1 2 3 4
1 2 3 4
[[1, 2, 3, 4], [1, 2, 3, 4]] 2 2
20


ValueError: Matrix must be square for opposite diagonal sum